### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by ShawnGeller** [hawkjo/ConstantMarginalIterator#1]
Hi there! I came across this code from looking at a stackexchange post that linked to it. I'd like to use this code, but there's no license, so I don't think I can legally do so. What license did you intend for this code?

Thanks,
Shawn

**Comment by hawkjo** [comment]
Howdy. Happy for you to use it as you will. Just added a MIT license.

**Comment by ShawnGeller** [comment]
Thanks!
